# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from revdoku_api.models.account_identity_agency_account import AccountIdentityAgencyAccount
from revdoku_api.models.account_identity_permissions import AccountIdentityPermissions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountIdentity(BaseModel):
    """
    AccountIdentity
    """ # noqa: E501
    id: StrictStr
    name: StrictStr = Field(description="Account name, separate from the client person or business.")
    account_kind: StrictStr
    client_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(description="Client person or business name, or null when unset.")
    agency_account: Optional[AccountIdentityAgencyAccount]
    region: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    permissions: Optional[AccountIdentityPermissions] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "name", "account_kind", "client_name", "agency_account", "region", "status", "permissions"]

    @field_validator('account_kind')
    def account_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['standard', 'agency', 'client']):
            raise ValueError("must be one of enum values ('standard', 'agency', 'client')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'read_only']):
            raise ValueError("must be one of enum values ('active', 'read_only')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountIdentity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agency_account
        if self.agency_account:
            _dict['agency_account'] = self.agency_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of permissions
        if self.permissions:
            _dict['permissions'] = self.permissions.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if client_name (nullable) is None
        # and model_fields_set contains the field
        if self.client_name is None and "client_name" in self.model_fields_set:
            _dict['client_name'] = None

        # set to None if agency_account (nullable) is None
        # and model_fields_set contains the field
        if self.agency_account is None and "agency_account" in self.model_fields_set:
            _dict['agency_account'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountIdentity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "account_kind": obj.get("account_kind"),
            "client_name": obj.get("client_name"),
            "agency_account": AccountIdentityAgencyAccount.from_dict(obj["agency_account"]) if obj.get("agency_account") is not None else None,
            "region": obj.get("region"),
            "status": obj.get("status"),
            "permissions": AccountIdentityPermissions.from_dict(obj["permissions"]) if obj.get("permissions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


