# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountLimits(BaseModel):
    """
    AccountLimits
    """ # noqa: E501
    max_mailboxes: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_mailbox_creations_per_month: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_files_per_mailbox: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_current_files: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_storage_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_file_size_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_pdf_size_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_file_versions_per_file: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_email_domains: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_received_emails_per_month: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_received_email_bytes_per_month: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_received_email_message_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_email_address_rotations_per_month: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_account_members: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_api_keys: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_agent_connections: Optional[Annotated[int, Field(strict=True, ge=0)]]
    api_rate_limit_requests_per_minute: Optional[Annotated[int, Field(strict=True, ge=0)]]
    audit_retention_days: Optional[Annotated[int, Field(strict=True, ge=0)]]
    max_email_aliases_per_mailbox: Annotated[int, Field(strict=True, ge=0)] = Field(description="Active retained email addresses per mailbox; Free always has zero.")
    __properties: ClassVar[List[str]] = ["max_mailboxes", "max_mailbox_creations_per_month", "max_files_per_mailbox", "max_current_files", "max_storage_bytes", "max_file_size_bytes", "max_pdf_size_bytes", "max_file_versions_per_file", "max_email_domains", "max_received_emails_per_month", "max_received_email_bytes_per_month", "max_received_email_message_bytes", "max_email_address_rotations_per_month", "max_account_members", "max_api_keys", "max_agent_connections", "api_rate_limit_requests_per_minute", "audit_retention_days", "max_email_aliases_per_mailbox"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_mailboxes (nullable) is None
        # and model_fields_set contains the field
        if self.max_mailboxes is None and "max_mailboxes" in self.model_fields_set:
            _dict['max_mailboxes'] = None

        # set to None if max_mailbox_creations_per_month (nullable) is None
        # and model_fields_set contains the field
        if self.max_mailbox_creations_per_month is None and "max_mailbox_creations_per_month" in self.model_fields_set:
            _dict['max_mailbox_creations_per_month'] = None

        # set to None if max_files_per_mailbox (nullable) is None
        # and model_fields_set contains the field
        if self.max_files_per_mailbox is None and "max_files_per_mailbox" in self.model_fields_set:
            _dict['max_files_per_mailbox'] = None

        # set to None if max_current_files (nullable) is None
        # and model_fields_set contains the field
        if self.max_current_files is None and "max_current_files" in self.model_fields_set:
            _dict['max_current_files'] = None

        # set to None if max_storage_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.max_storage_bytes is None and "max_storage_bytes" in self.model_fields_set:
            _dict['max_storage_bytes'] = None

        # set to None if max_file_size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.max_file_size_bytes is None and "max_file_size_bytes" in self.model_fields_set:
            _dict['max_file_size_bytes'] = None

        # set to None if max_pdf_size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.max_pdf_size_bytes is None and "max_pdf_size_bytes" in self.model_fields_set:
            _dict['max_pdf_size_bytes'] = None

        # set to None if max_file_versions_per_file (nullable) is None
        # and model_fields_set contains the field
        if self.max_file_versions_per_file is None and "max_file_versions_per_file" in self.model_fields_set:
            _dict['max_file_versions_per_file'] = None

        # set to None if max_email_domains (nullable) is None
        # and model_fields_set contains the field
        if self.max_email_domains is None and "max_email_domains" in self.model_fields_set:
            _dict['max_email_domains'] = None

        # set to None if max_received_emails_per_month (nullable) is None
        # and model_fields_set contains the field
        if self.max_received_emails_per_month is None and "max_received_emails_per_month" in self.model_fields_set:
            _dict['max_received_emails_per_month'] = None

        # set to None if max_received_email_bytes_per_month (nullable) is None
        # and model_fields_set contains the field
        if self.max_received_email_bytes_per_month is None and "max_received_email_bytes_per_month" in self.model_fields_set:
            _dict['max_received_email_bytes_per_month'] = None

        # set to None if max_received_email_message_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.max_received_email_message_bytes is None and "max_received_email_message_bytes" in self.model_fields_set:
            _dict['max_received_email_message_bytes'] = None

        # set to None if max_email_address_rotations_per_month (nullable) is None
        # and model_fields_set contains the field
        if self.max_email_address_rotations_per_month is None and "max_email_address_rotations_per_month" in self.model_fields_set:
            _dict['max_email_address_rotations_per_month'] = None

        # set to None if max_account_members (nullable) is None
        # and model_fields_set contains the field
        if self.max_account_members is None and "max_account_members" in self.model_fields_set:
            _dict['max_account_members'] = None

        # set to None if max_api_keys (nullable) is None
        # and model_fields_set contains the field
        if self.max_api_keys is None and "max_api_keys" in self.model_fields_set:
            _dict['max_api_keys'] = None

        # set to None if max_agent_connections (nullable) is None
        # and model_fields_set contains the field
        if self.max_agent_connections is None and "max_agent_connections" in self.model_fields_set:
            _dict['max_agent_connections'] = None

        # set to None if api_rate_limit_requests_per_minute (nullable) is None
        # and model_fields_set contains the field
        if self.api_rate_limit_requests_per_minute is None and "api_rate_limit_requests_per_minute" in self.model_fields_set:
            _dict['api_rate_limit_requests_per_minute'] = None

        # set to None if audit_retention_days (nullable) is None
        # and model_fields_set contains the field
        if self.audit_retention_days is None and "audit_retention_days" in self.model_fields_set:
            _dict['audit_retention_days'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "max_mailboxes": obj.get("max_mailboxes"),
            "max_mailbox_creations_per_month": obj.get("max_mailbox_creations_per_month"),
            "max_files_per_mailbox": obj.get("max_files_per_mailbox"),
            "max_current_files": obj.get("max_current_files"),
            "max_storage_bytes": obj.get("max_storage_bytes"),
            "max_file_size_bytes": obj.get("max_file_size_bytes"),
            "max_pdf_size_bytes": obj.get("max_pdf_size_bytes"),
            "max_file_versions_per_file": obj.get("max_file_versions_per_file"),
            "max_email_domains": obj.get("max_email_domains"),
            "max_received_emails_per_month": obj.get("max_received_emails_per_month"),
            "max_received_email_bytes_per_month": obj.get("max_received_email_bytes_per_month"),
            "max_received_email_message_bytes": obj.get("max_received_email_message_bytes"),
            "max_email_address_rotations_per_month": obj.get("max_email_address_rotations_per_month"),
            "max_account_members": obj.get("max_account_members"),
            "max_api_keys": obj.get("max_api_keys"),
            "max_agent_connections": obj.get("max_agent_connections"),
            "api_rate_limit_requests_per_minute": obj.get("api_rate_limit_requests_per_minute"),
            "audit_retention_days": obj.get("audit_retention_days"),
            "max_email_aliases_per_mailbox": obj.get("max_email_aliases_per_mailbox")
        })
        return _obj


