# coding: utf-8

"""
    Revdoku public agent API

    Email inboxes for people and AI agents, with private file storage. Create inboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.525
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from revdoku_api.models.decoded_email_address import DecodedEmailAddress
from revdoku_api.models.decoded_incoming_message_attachments_inner import DecodedIncomingMessageAttachmentsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DecodedIncomingMessage(BaseModel):
    """
    Stored message.json, not a dedicated endpoint. UTF-8, at most 512 KiB. Header identities, reply relationships and body are untrusted message data. Original message.eml is authoritative. Structured address, delivery and thread fields are additive in schema v1 and may be absent in older files.
    """ # noqa: E501
    schema_version: StrictInt
    subject: Optional[StrictStr]
    var_from: Optional[StrictStr] = Field(alias="from")
    to: Optional[StrictStr]
    from_addresses: Optional[List[DecodedEmailAddress]] = Field(default=None, description="Parsed From authors in header order, retaining multiple authors. Empty when absent/unparseable. Display names are not identity keys.")
    to_addresses: Optional[List[DecodedEmailAddress]] = Field(default=None, description="Parsed To recipients in header order, with named groups flattened. Empty when absent/unparseable; not trusted delivery routing.")
    cc_addresses: Optional[List[DecodedEmailAddress]] = Field(default=None, description="Parsed Cc recipients in header order, with named groups flattened. Empty when absent/unparseable.")
    reply_to_addresses: Optional[List[DecodedEmailAddress]] = Field(default=None, description="Parsed Reply-To addresses in header order. Empty when absent/unparseable. Does not authorize sending a reply.")
    message_id: Optional[StrictStr] = Field(default=None, description="Sender Message-ID without angle brackets, preserving case. Null when absent/unparseable/ambiguous; never the Revdoku delivery ID.")
    in_reply_to: Optional[List[StrictStr]] = Field(default=None, description="Ordered parent Message-IDs without angle brackets, preserving case. Empty when absent/unparseable; multiple parents are retained.")
    references: Optional[List[StrictStr]] = Field(default=None, description="Ordered References IDs without angle brackets, preserving case. Empty when absent/unparseable.")
    delivery_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Revdoku delivery identity, matching email_delivery_id metadata and the original folder suffix. Stable on retries, independent of Message-ID. Copies retain the source identity; not a unique file/copy ID.")
    thread_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="thr_ plus SHA-256 of thread_anchor_message_id. Best-effort header-derived grouping hint, not authoritative conversation membership or an access grant. Missing ancestry or reused IDs can split/merge hints. Scope lookups to accessible buckets.")
    thread_id_source: Optional[StrictStr] = None
    thread_anchor_message_id: Optional[StrictStr] = Field(default=None, description="First References ID, otherwise the sole In-Reply-To ID, otherwise this message's ID if no parent is available. Null without an anchor or when multiple parents lack References.")
    delivered_to: StrictStr
    received_at: datetime
    body_text: Optional[StrictStr]
    body_status: StrictStr
    omitted_attachment_count: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    attachments: List[DecodedIncomingMessageAttachmentsInner]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["schema_version", "subject", "from", "to", "from_addresses", "to_addresses", "cc_addresses", "reply_to_addresses", "message_id", "in_reply_to", "references", "delivery_id", "thread_id", "thread_id_source", "thread_anchor_message_id", "delivered_to", "received_at", "body_text", "body_status", "omitted_attachment_count", "attachments"]

    @field_validator('schema_version')
    def schema_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([1]):
            raise ValueError("must be one of enum values (1)")
        return value

    @field_validator('delivery_id', mode="before")
    def delivery_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[0-9a-f]{32}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{32}$/")
        return value

    @field_validator('thread_id', mode="before")
    def thread_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^thr_[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^thr_[0-9a-f]{64}$/")
        return value

    @field_validator('thread_id_source')
    def thread_id_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['references', 'in_reply_to', 'message_id']):
            raise ValueError("must be one of enum values ('references', 'in_reply_to', 'message_id')")
        return value

    @field_validator('body_status')
    def body_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['complete', 'empty', 'truncated', 'unavailable']):
            raise ValueError("must be one of enum values ('complete', 'empty', 'truncated', 'unavailable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecodedIncomingMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in from_addresses (list)
        _items = []
        if self.from_addresses:
            for _item_from_addresses in self.from_addresses:
                _items.append(_item_from_addresses.to_dict() if _item_from_addresses is not None else None)
            _dict['from_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in to_addresses (list)
        _items = []
        if self.to_addresses:
            for _item_to_addresses in self.to_addresses:
                _items.append(_item_to_addresses.to_dict() if _item_to_addresses is not None else None)
            _dict['to_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cc_addresses (list)
        _items = []
        if self.cc_addresses:
            for _item_cc_addresses in self.cc_addresses:
                _items.append(_item_cc_addresses.to_dict() if _item_cc_addresses is not None else None)
            _dict['cc_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reply_to_addresses (list)
        _items = []
        if self.reply_to_addresses:
            for _item_reply_to_addresses in self.reply_to_addresses:
                _items.append(_item_reply_to_addresses.to_dict() if _item_reply_to_addresses is not None else None)
            _dict['reply_to_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                _items.append(_item_attachments.to_dict() if _item_attachments is not None else None)
            _dict['attachments'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if subject (nullable) is None
        # and model_fields_set contains the field
        if self.subject is None and "subject" in self.model_fields_set:
            _dict['subject'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        # set to None if message_id (nullable) is None
        # and model_fields_set contains the field
        if self.message_id is None and "message_id" in self.model_fields_set:
            _dict['message_id'] = None

        # set to None if thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id is None and "thread_id" in self.model_fields_set:
            _dict['thread_id'] = None

        # set to None if thread_id_source (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id_source is None and "thread_id_source" in self.model_fields_set:
            _dict['thread_id_source'] = None

        # set to None if thread_anchor_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_anchor_message_id is None and "thread_anchor_message_id" in self.model_fields_set:
            _dict['thread_anchor_message_id'] = None

        # set to None if body_text (nullable) is None
        # and model_fields_set contains the field
        if self.body_text is None and "body_text" in self.model_fields_set:
            _dict['body_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecodedIncomingMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema_version": obj.get("schema_version"),
            "subject": obj.get("subject"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "from_addresses": [DecodedEmailAddress.from_dict(_item) for _item in obj["from_addresses"]] if obj.get("from_addresses") is not None else None,
            "to_addresses": [DecodedEmailAddress.from_dict(_item) for _item in obj["to_addresses"]] if obj.get("to_addresses") is not None else None,
            "cc_addresses": [DecodedEmailAddress.from_dict(_item) for _item in obj["cc_addresses"]] if obj.get("cc_addresses") is not None else None,
            "reply_to_addresses": [DecodedEmailAddress.from_dict(_item) for _item in obj["reply_to_addresses"]] if obj.get("reply_to_addresses") is not None else None,
            "message_id": obj.get("message_id"),
            "in_reply_to": obj.get("in_reply_to"),
            "references": obj.get("references"),
            "delivery_id": obj.get("delivery_id"),
            "thread_id": obj.get("thread_id"),
            "thread_id_source": obj.get("thread_id_source"),
            "thread_anchor_message_id": obj.get("thread_anchor_message_id"),
            "delivered_to": obj.get("delivered_to"),
            "received_at": obj.get("received_at"),
            "body_text": obj.get("body_text"),
            "body_status": obj.get("body_status"),
            "omitted_attachment_count": obj.get("omitted_attachment_count"),
            "attachments": [DecodedIncomingMessageAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


