# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.535
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmailForwardingContent(BaseModel):
    """
    EmailForwardingContent
    """ # noqa: E501
    method: StrictStr
    member_id: StrictStr
    member_email: StrictStr
    intake_account_id: StrictStr
    outer_from: Optional[StrictStr] = None
    outer_subject: Optional[StrictStr] = None
    outer_message_id: Optional[StrictStr] = None
    original_date_raw: Optional[StrictStr] = None
    original_sent_at: Optional[StrictStr] = None
    attribution: StrictStr
    parser_version: Annotated[int, Field(strict=True, ge=1)] = Field(description="Parser implementation used at intake; does not change the forwarding response shape.")
    note_text: Optional[StrictStr] = Field(default=None, description="Separate member note, bounded to 64 KiB. Never part of the original body.")
    note_status: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["method", "member_id", "member_email", "intake_account_id", "outer_from", "outer_subject", "outer_message_id", "original_date_raw", "original_sent_at", "attribution", "parser_version", "note_text", "note_status"]

    @field_validator('attribution')
    def attribution_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['member_forwarded']):
            raise ValueError("must be one of enum values ('member_forwarded')")
        return value

    @field_validator('note_status')
    def note_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['complete', 'empty', 'truncated', 'unavailable']):
            raise ValueError("must be one of enum values ('complete', 'empty', 'truncated', 'unavailable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailForwardingContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailForwardingContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method"),
            "member_id": obj.get("member_id"),
            "member_email": obj.get("member_email"),
            "intake_account_id": obj.get("intake_account_id"),
            "outer_from": obj.get("outer_from"),
            "outer_subject": obj.get("outer_subject"),
            "outer_message_id": obj.get("outer_message_id"),
            "original_date_raw": obj.get("original_date_raw"),
            "original_sent_at": obj.get("original_sent_at"),
            "attribution": obj.get("attribution"),
            "parser_version": obj.get("parser_version"),
            "note_text": obj.get("note_text"),
            "note_status": obj.get("note_status")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


