# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revdoku_api.models.dns_record import DnsRecord
from revdoku_api.models.email_domain_assigned_mailboxes_inner import EmailDomainAssignedMailboxesInner
from revdoku_api.models.email_domain_error import EmailDomainError
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmailDomain(BaseModel):
    """
    EmailDomain
    """ # noqa: E501
    suggested_subdomain: Optional[StrictStr] = None
    root_guidance: Optional[StrictStr] = None
    pause_reason: Optional[StrictStr] = None
    id: StrictStr
    hostname: StrictStr
    status: StrictStr
    guidance: Optional[StrictStr] = None
    receiving: Optional[StrictBool] = None
    root_domain: Optional[StrictBool] = None
    paused_at: Optional[datetime] = None
    last_checked_at: Optional[datetime] = None
    ownership_verified_at: Optional[datetime] = None
    setup_expires_at: Optional[datetime] = None
    ready_at: Optional[datetime] = None
    required_dns_records: Optional[List[DnsRecord]] = None
    error: Optional[EmailDomainError] = None
    assigned_mailboxes: Optional[List[EmailDomainAssignedMailboxesInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["suggested_subdomain", "root_guidance", "pause_reason", "id", "hostname", "status", "guidance", "receiving", "root_domain", "paused_at", "last_checked_at", "ownership_verified_at", "setup_expires_at", "ready_at", "required_dns_records", "error", "assigned_mailboxes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in required_dns_records (list)
        _items = []
        if self.required_dns_records:
            for _item_required_dns_records in self.required_dns_records:
                _items.append(_item_required_dns_records.to_dict() if _item_required_dns_records is not None else None)
            _dict['required_dns_records'] = _items
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in assigned_mailboxes (list)
        _items = []
        if self.assigned_mailboxes:
            for _item_assigned_mailboxes in self.assigned_mailboxes:
                _items.append(_item_assigned_mailboxes.to_dict() if _item_assigned_mailboxes is not None else None)
            _dict['assigned_mailboxes'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if suggested_subdomain (nullable) is None
        # and model_fields_set contains the field
        if self.suggested_subdomain is None and "suggested_subdomain" in self.model_fields_set:
            _dict['suggested_subdomain'] = None

        # set to None if root_guidance (nullable) is None
        # and model_fields_set contains the field
        if self.root_guidance is None and "root_guidance" in self.model_fields_set:
            _dict['root_guidance'] = None

        # set to None if pause_reason (nullable) is None
        # and model_fields_set contains the field
        if self.pause_reason is None and "pause_reason" in self.model_fields_set:
            _dict['pause_reason'] = None

        # set to None if paused_at (nullable) is None
        # and model_fields_set contains the field
        if self.paused_at is None and "paused_at" in self.model_fields_set:
            _dict['paused_at'] = None

        # set to None if last_checked_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_checked_at is None and "last_checked_at" in self.model_fields_set:
            _dict['last_checked_at'] = None

        # set to None if ownership_verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.ownership_verified_at is None and "ownership_verified_at" in self.model_fields_set:
            _dict['ownership_verified_at'] = None

        # set to None if setup_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.setup_expires_at is None and "setup_expires_at" in self.model_fields_set:
            _dict['setup_expires_at'] = None

        # set to None if ready_at (nullable) is None
        # and model_fields_set contains the field
        if self.ready_at is None and "ready_at" in self.model_fields_set:
            _dict['ready_at'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "suggested_subdomain": obj.get("suggested_subdomain"),
            "root_guidance": obj.get("root_guidance"),
            "pause_reason": obj.get("pause_reason"),
            "id": obj.get("id"),
            "hostname": obj.get("hostname"),
            "status": obj.get("status"),
            "guidance": obj.get("guidance"),
            "receiving": obj.get("receiving"),
            "root_domain": obj.get("root_domain"),
            "paused_at": obj.get("paused_at"),
            "last_checked_at": obj.get("last_checked_at"),
            "ownership_verified_at": obj.get("ownership_verified_at"),
            "setup_expires_at": obj.get("setup_expires_at"),
            "ready_at": obj.get("ready_at"),
            "required_dns_records": [DnsRecord.from_dict(_item) for _item in obj["required_dns_records"]] if obj.get("required_dns_records") is not None else None,
            "error": EmailDomainError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "assigned_mailboxes": [EmailDomainAssignedMailboxesInner.from_dict(_item) for _item in obj["assigned_mailboxes"]] if obj.get("assigned_mailboxes") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


