# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revdoku_api.models.file_actor import FileActor
from revdoku_api.models.file_key import FileKey
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FileVersion(BaseModel):
    """
    FileVersion
    """ # noqa: E501
    id: Optional[StrictStr] = None
    file_id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    mime_type: Optional[StrictStr] = None
    sha256: Optional[StrictStr] = None
    reason: Optional[StrictStr] = None
    meta_key: Optional[StrictStr] = None
    created_by_system: Optional[StrictStr] = None
    deleted: Optional[StrictBool] = None
    ready: Optional[StrictBool] = None
    has_text: Optional[StrictBool] = None
    normalization_required: Optional[StrictBool] = None
    meta_ready: Optional[StrictBool] = None
    version_number: Optional[StrictInt] = None
    byte_size: Optional[StrictInt] = None
    created_at: Optional[datetime] = None
    meta_created_at: Optional[datetime] = None
    created_by: Optional[FileActor] = None
    updated_by: Optional[FileActor] = None
    created_by_agent: Optional[Dict[str, Any]] = None
    updated_by_agent: Optional[Dict[str, Any]] = None
    created_by_api_key: Optional[Dict[str, Any]] = None
    updated_by_api_key: Optional[Dict[str, Any]] = None
    read: Optional[StrictBool] = None
    read_at: Optional[datetime] = None
    read_by: Optional[FileActor] = None
    read_by_api_key: Optional[FileKey] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "file_id", "name", "mime_type", "sha256", "reason", "meta_key", "created_by_system", "deleted", "ready", "has_text", "normalization_required", "meta_ready", "version_number", "byte_size", "created_at", "meta_created_at", "created_by", "updated_by", "created_by_agent", "updated_by_agent", "created_by_api_key", "updated_by_api_key", "read", "read_at", "read_by", "read_by_api_key"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updated_by'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of read_by
        if self.read_by:
            _dict['read_by'] = self.read_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of read_by_api_key
        if self.read_by_api_key:
            _dict['read_by_api_key'] = self.read_by_api_key.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if read_at (nullable) is None
        # and model_fields_set contains the field
        if self.read_at is None and "read_at" in self.model_fields_set:
            _dict['read_at'] = None

        # set to None if read_by (nullable) is None
        # and model_fields_set contains the field
        if self.read_by is None and "read_by" in self.model_fields_set:
            _dict['read_by'] = None

        # set to None if read_by_api_key (nullable) is None
        # and model_fields_set contains the field
        if self.read_by_api_key is None and "read_by_api_key" in self.model_fields_set:
            _dict['read_by_api_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "file_id": obj.get("file_id"),
            "name": obj.get("name"),
            "mime_type": obj.get("mime_type"),
            "sha256": obj.get("sha256"),
            "reason": obj.get("reason"),
            "meta_key": obj.get("meta_key"),
            "created_by_system": obj.get("created_by_system"),
            "deleted": obj.get("deleted"),
            "ready": obj.get("ready"),
            "has_text": obj.get("has_text"),
            "normalization_required": obj.get("normalization_required"),
            "meta_ready": obj.get("meta_ready"),
            "version_number": obj.get("version_number"),
            "byte_size": obj.get("byte_size"),
            "created_at": obj.get("created_at"),
            "meta_created_at": obj.get("meta_created_at"),
            "created_by": FileActor.from_dict(obj["created_by"]) if obj.get("created_by") is not None else None,
            "updated_by": FileActor.from_dict(obj["updated_by"]) if obj.get("updated_by") is not None else None,
            "created_by_agent": obj.get("created_by_agent"),
            "updated_by_agent": obj.get("updated_by_agent"),
            "created_by_api_key": obj.get("created_by_api_key"),
            "updated_by_api_key": obj.get("updated_by_api_key"),
            "read": obj.get("read"),
            "read_at": obj.get("read_at"),
            "read_by": FileActor.from_dict(obj["read_by"]) if obj.get("read_by") is not None else None,
            "read_by_api_key": FileKey.from_dict(obj["read_by_api_key"]) if obj.get("read_by_api_key") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


