# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revdoku_api.models.account_identity import AccountIdentity
from revdoku_api.models.get_revdoku_status200_response_data_connection import GetRevdokuStatus200ResponseDataConnection
from revdoku_api.models.get_revdoku_status200_response_data_features import GetRevdokuStatus200ResponseDataFeatures
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRevdokuStatus200ResponseData(BaseModel):
    """
    GetRevdokuStatus200ResponseData
    """ # noqa: E501
    account: Optional[AccountIdentity] = None
    default_account_id: Optional[StrictStr] = None
    accounts: Optional[List[AccountIdentity]] = None
    features: Optional[GetRevdokuStatus200ResponseDataFeatures] = None
    connected: Optional[StrictBool] = None
    server_version: Optional[StrictStr] = None
    client_version: Optional[StrictStr] = None
    connection: Optional[GetRevdokuStatus200ResponseDataConnection] = None
    limits: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["account", "default_account_id", "accounts", "features", "connected", "server_version", "client_version", "connection", "limits"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRevdokuStatus200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                _items.append(_item_accounts.to_dict() if _item_accounts is not None else None)
            _dict['accounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connection
        if self.connection:
            _dict['connection'] = self.connection.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if default_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_account_id is None and "default_account_id" in self.model_fields_set:
            _dict['default_account_id'] = None

        # set to None if limits (nullable) is None
        # and model_fields_set contains the field
        if self.limits is None and "limits" in self.model_fields_set:
            _dict['limits'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRevdokuStatus200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": AccountIdentity.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "default_account_id": obj.get("default_account_id"),
            "accounts": [AccountIdentity.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
            "features": GetRevdokuStatus200ResponseDataFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "connected": obj.get("connected"),
            "server_version": obj.get("server_version"),
            "client_version": obj.get("client_version"),
            "connection": GetRevdokuStatus200ResponseDataConnection.from_dict(obj["connection"]) if obj.get("connection") is not None else None,
            "limits": obj.get("limits")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


