# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revdoku_api.models.get_revdoku_status200_response_data_connection_renewal import GetRevdokuStatus200ResponseDataConnectionRenewal
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRevdokuStatus200ResponseDataConnection(BaseModel):
    """
    GetRevdokuStatus200ResponseDataConnection
    """ # noqa: E501
    api_key_id: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    token_type: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    expires_at: Optional[datetime] = None
    last_used_at: Optional[datetime] = None
    mailbox_access: Optional[StrictStr] = None
    mailbox_ids: Optional[List[StrictStr]] = None
    denied_mailbox_ids: Optional[List[StrictStr]] = None
    mailbox_permissions: Optional[Dict[str, StrictStr]] = None
    permissions: Optional[Dict[str, StrictBool]] = None
    agent: Optional[Dict[str, Any]] = None
    transport: Optional[StrictStr] = None
    renewal: Optional[GetRevdokuStatus200ResponseDataConnectionRenewal] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["api_key_id", "label", "token_type", "scope", "expires_at", "last_used_at", "mailbox_access", "mailbox_ids", "denied_mailbox_ids", "mailbox_permissions", "permissions", "agent", "transport", "renewal"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRevdokuStatus200ResponseDataConnection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of renewal
        if self.renewal:
            _dict['renewal'] = self.renewal.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_id is None and "api_key_id" in self.model_fields_set:
            _dict['api_key_id'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if token_type (nullable) is None
        # and model_fields_set contains the field
        if self.token_type is None and "token_type" in self.model_fields_set:
            _dict['token_type'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['last_used_at'] = None

        # set to None if mailbox_access (nullable) is None
        # and model_fields_set contains the field
        if self.mailbox_access is None and "mailbox_access" in self.model_fields_set:
            _dict['mailbox_access'] = None

        # set to None if agent (nullable) is None
        # and model_fields_set contains the field
        if self.agent is None and "agent" in self.model_fields_set:
            _dict['agent'] = None

        # set to None if transport (nullable) is None
        # and model_fields_set contains the field
        if self.transport is None and "transport" in self.model_fields_set:
            _dict['transport'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRevdokuStatus200ResponseDataConnection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key_id": obj.get("api_key_id"),
            "label": obj.get("label"),
            "token_type": obj.get("token_type"),
            "scope": obj.get("scope"),
            "expires_at": obj.get("expires_at"),
            "last_used_at": obj.get("last_used_at"),
            "mailbox_access": obj.get("mailbox_access"),
            "mailbox_ids": obj.get("mailbox_ids"),
            "denied_mailbox_ids": obj.get("denied_mailbox_ids"),
            "mailbox_permissions": obj.get("mailbox_permissions"),
            "permissions": obj.get("permissions"),
            "agent": obj.get("agent"),
            "transport": obj.get("transport"),
            "renewal": GetRevdokuStatus200ResponseDataConnectionRenewal.from_dict(obj["renewal"]) if obj.get("renewal") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


