# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from revdoku_api.models.email_sender_allowlist import EmailSenderAllowlist
from revdoku_api.models.mailbox_email_aliases_inner import MailboxEmailAliasesInner
from revdoku_api.models.mailbox_email_assignment import MailboxEmailAssignment
from revdoku_api.models.mailbox_email_available_domains_inner import MailboxEmailAvailableDomainsInner
from revdoku_api.models.mailbox_email_customization import MailboxEmailCustomization
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailboxEmail(BaseModel):
    """
    Receiving address/state on creation and authorized opt-in reads. Ordinary mailbox reads expose activity only; use the emails collection for a durable arrival cursor.
    """ # noqa: E501
    address: Optional[StrictStr] = None
    received_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    last_received_at: Optional[datetime] = None
    last_received_path: Optional[StrictStr] = Field(default=None, description="Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.")
    blocked_reason: Optional[StrictStr] = Field(default=None, description="Why receiving is unavailable; omitted when receiving_enabled is true.")
    available_domains: Optional[List[MailboxEmailAvailableDomainsInner]] = None
    assignment: Optional[MailboxEmailAssignment] = None
    customization: Optional[MailboxEmailCustomization] = None
    receiving_enabled: Optional[StrictBool] = Field(default=None, description="Whether this mailbox can currently receive email. False when configuration, account state, quota or routing prevents receiving.")
    sender_allowlist: Optional[EmailSenderAllowlist] = None
    username: Optional[StrictStr] = None
    sending_enabled: Optional[StrictBool] = Field(default=None, description="Always false. Sending is not implemented.")
    aliases: Optional[List[MailboxEmailAliasesInner]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["address", "received_count", "last_received_at", "last_received_path", "blocked_reason", "available_domains", "assignment", "customization", "receiving_enabled", "sender_allowlist", "username", "sending_enabled", "aliases"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailboxEmail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_domains (list)
        _items = []
        if self.available_domains:
            for _item_available_domains in self.available_domains:
                _items.append(_item_available_domains.to_dict() if _item_available_domains is not None else None)
            _dict['available_domains'] = _items
        # override the default output from pydantic by calling `to_dict()` of assignment
        if self.assignment:
            _dict['assignment'] = self.assignment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customization
        if self.customization:
            _dict['customization'] = self.customization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sender_allowlist
        if self.sender_allowlist:
            _dict['sender_allowlist'] = self.sender_allowlist.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in aliases (list)
        _items = []
        if self.aliases:
            for _item_aliases in self.aliases:
                _items.append(_item_aliases.to_dict() if _item_aliases is not None else None)
            _dict['aliases'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if last_received_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_received_at is None and "last_received_at" in self.model_fields_set:
            _dict['last_received_at'] = None

        # set to None if last_received_path (nullable) is None
        # and model_fields_set contains the field
        if self.last_received_path is None and "last_received_path" in self.model_fields_set:
            _dict['last_received_path'] = None

        # set to None if blocked_reason (nullable) is None
        # and model_fields_set contains the field
        if self.blocked_reason is None and "blocked_reason" in self.model_fields_set:
            _dict['blocked_reason'] = None

        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict['username'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailboxEmail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "received_count": obj.get("received_count"),
            "last_received_at": obj.get("last_received_at"),
            "last_received_path": obj.get("last_received_path"),
            "blocked_reason": obj.get("blocked_reason"),
            "available_domains": [MailboxEmailAvailableDomainsInner.from_dict(_item) for _item in obj["available_domains"]] if obj.get("available_domains") is not None else None,
            "assignment": MailboxEmailAssignment.from_dict(obj["assignment"]) if obj.get("assignment") is not None else None,
            "customization": MailboxEmailCustomization.from_dict(obj["customization"]) if obj.get("customization") is not None else None,
            "receiving_enabled": obj.get("receiving_enabled"),
            "sender_allowlist": EmailSenderAllowlist.from_dict(obj["sender_allowlist"]) if obj.get("sender_allowlist") is not None else None,
            "username": obj.get("username"),
            "sending_enabled": obj.get("sending_enabled"),
            "aliases": [MailboxEmailAliasesInner.from_dict(_item) for _item in obj["aliases"]] if obj.get("aliases") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


