# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from revdoku_api.models.mailbox_action import MailboxAction
from revdoku_api.models.mailbox_email import MailboxEmail
from revdoku_api.models.mailbox_lock import MailboxLock
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Mailbox(BaseModel):
    """
    Public mailbox details. Ordinary reads include email activity only; creation and authorized include_email reads also include receiving addresses.
    """ # noqa: E501
    id: StrictStr
    account_id: StrictStr
    title: StrictStr
    description: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    metadata_version: Optional[StrictStr] = None
    email: MailboxEmail
    archived: Optional[StrictBool] = None
    archived_at: Optional[datetime] = None
    lock: Optional[MailboxLock] = None
    storage_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    files_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    dashboard_url: Optional[StrictStr] = None
    current_mailbox_revision_id: Optional[StrictStr] = None
    current_mailbox_revision_number: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    archive: Optional[MailboxAction] = None
    unarchive: Optional[MailboxAction] = None
    delete: Optional[MailboxAction] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "account_id", "title", "description", "metadata", "metadata_version", "email", "archived", "archived_at", "lock", "storage_bytes", "files_count", "created_at", "updated_at", "dashboard_url", "current_mailbox_revision_id", "current_mailbox_revision_number", "archive", "unarchive", "delete"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mailbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of email
        if self.email:
            _dict['email'] = self.email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lock
        if self.lock:
            _dict['lock'] = self.lock.to_dict()
        # override the default output from pydantic by calling `to_dict()` of archive
        if self.archive:
            _dict['archive'] = self.archive.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unarchive
        if self.unarchive:
            _dict['unarchive'] = self.unarchive.to_dict()
        # override the default output from pydantic by calling `to_dict()` of delete
        if self.delete:
            _dict['delete'] = self.delete.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if archived_at (nullable) is None
        # and model_fields_set contains the field
        if self.archived_at is None and "archived_at" in self.model_fields_set:
            _dict['archived_at'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if current_mailbox_revision_id (nullable) is None
        # and model_fields_set contains the field
        if self.current_mailbox_revision_id is None and "current_mailbox_revision_id" in self.model_fields_set:
            _dict['current_mailbox_revision_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mailbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "account_id": obj.get("account_id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "metadata_version": obj.get("metadata_version"),
            "email": MailboxEmail.from_dict(obj["email"]) if obj.get("email") is not None else None,
            "archived": obj.get("archived"),
            "archived_at": obj.get("archived_at"),
            "lock": MailboxLock.from_dict(obj["lock"]) if obj.get("lock") is not None else None,
            "storage_bytes": obj.get("storage_bytes"),
            "files_count": obj.get("files_count"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "dashboard_url": obj.get("dashboard_url"),
            "current_mailbox_revision_id": obj.get("current_mailbox_revision_id"),
            "current_mailbox_revision_number": obj.get("current_mailbox_revision_number"),
            "archive": MailboxAction.from_dict(obj["archive"]) if obj.get("archive") is not None else None,
            "unarchive": MailboxAction.from_dict(obj["unarchive"]) if obj.get("unarchive") is not None else None,
            "delete": MailboxAction.from_dict(obj["delete"]) if obj.get("delete") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


