# coding: utf-8

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revdoku_api.models.file_version import FileVersion
from revdoku_api.models.mailbox_file import MailboxFile
from revdoku_api.models.storage_upload import StorageUpload
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PreparedFileUpload(BaseModel):
    """
    A new upload returns signed_id and direct_upload. Identical content returns skipped=true, duplicate=true, file and version without a storage upload.
    """ # noqa: E501
    signed_id: Optional[StrictStr] = None
    filename: Optional[StrictStr] = None
    byte_size: Optional[StrictInt] = None
    checksum: Optional[StrictStr] = None
    content_type: Optional[StrictStr] = None
    service_name: Optional[StrictStr] = None
    direct_upload: Optional[StorageUpload] = None
    file: Optional[MailboxFile] = None
    version: Optional[FileVersion] = None
    skipped: Optional[StrictBool] = None
    duplicate: Optional[StrictBool] = None
    reason: Optional[StrictStr] = None
    details: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["signed_id", "filename", "byte_size", "checksum", "content_type", "service_name", "direct_upload", "file", "version", "skipped", "duplicate", "reason", "details"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PreparedFileUpload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of direct_upload
        if self.direct_upload:
            _dict['direct_upload'] = self.direct_upload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PreparedFileUpload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signed_id": obj.get("signed_id"),
            "filename": obj.get("filename"),
            "byte_size": obj.get("byte_size"),
            "checksum": obj.get("checksum"),
            "content_type": obj.get("content_type"),
            "service_name": obj.get("service_name"),
            "direct_upload": StorageUpload.from_dict(obj["direct_upload"]) if obj.get("direct_upload") is not None else None,
            "file": MailboxFile.from_dict(obj["file"]) if obj.get("file") is not None else None,
            "version": FileVersion.from_dict(obj["version"]) if obj.get("version") is not None else None,
            "skipped": obj.get("skipped"),
            "duplicate": obj.get("duplicate"),
            "reason": obj.get("reason"),
            "details": obj.get("details")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


