# coding: utf-8

# flake8: noqa

"""
    Revdoku public agent API

    Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

    The version of the OpenAPI document: 1.0.535
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.535"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccountIdentity",
    "AccountIdentityAgencyAccount",
    "AccountIdentityPermissions",
    "AccountLimits",
    "AccountPagination",
    "ApiError",
    "ApiErrorError",
    "ApiErrorNot",
    "ApiSuccess",
    "CreateAccountEmailDomainRequest",
    "CreateClientAccount201Response",
    "CreateClientAccount201ResponseData",
    "CreateClientAccountRequest",
    "CreateMailbox201Response",
    "CreateMailbox201ResponseData",
    "CreateMailboxEmailAliasRequest",
    "CreateMailboxRequest",
    "CreateMailboxRequestMailbox",
    "CreateMailboxRequestMailboxEmail",
    "DecodedEmailAddress",
    "DecodedIncomingMessage",
    "DecodedIncomingMessageAttachmentsInner",
    "DownloadEmailOriginal200Response",
    "DownloadEmailOriginal200ResponseData",
    "EmailAttachment",
    "EmailDetail",
    "EmailDownload",
    "EmailForwarding",
    "EmailForwardingContent",
    "EmailPagination",
    "EmailReceivedEvent",
    "EmailReceivedEventData",
    "EmailSenderAllowlist",
    "EmailSummary",
    "EmailSummaryFiles",
    "FilePagination",
    "GetAccount200Response",
    "GetAccountLimits200Response",
    "GetAccountLimits200ResponseData",
    "GetAccountLimits200ResponseDataUsage",
    "GetAccountLimits200ResponseDataUsageMailboxCreations",
    "GetEmail200Response",
    "GetEmail200ResponseData",
    "GetEmailSubscription200Response",
    "GetEmailSubscription200ResponseData",
    "GetEmailSubscription200ResponseDataSubscription",
    "GetEmailWebhook200Response",
    "GetEmailWebhook200ResponseData",
    "GetEmailWebhook200ResponseDataWebhook",
    "GetMailboxEmailSettings200Response",
    "GetRevdokuStatus200Response",
    "GetRevdokuStatus200ResponseData",
    "GetRevdokuStatus200ResponseDataConnection",
    "GetRevdokuStatus200ResponseDataConnectionRenewal",
    "GetRevdokuStatus200ResponseDataFeatures",
    "GetRevdokuStatus200ResponseNot",
    "ListAccounts200Response",
    "ListAccounts200ResponseData",
    "ListEmails200Response",
    "ListEmails200ResponseData",
    "ListMailboxFiles200Response",
    "ListMailboxFiles200ResponseData",
    "ListMailboxes200Response",
    "ListMailboxes200ResponseData",
    "Mailbox",
    "MailboxAction",
    "MailboxEmail",
    "MailboxEmailActivity",
    "MailboxEmailAliasesInner",
    "MailboxEmailAssignment",
    "MailboxEmailAssignmentError",
    "MailboxEmailAvailableDomainsInner",
    "MailboxEmailCustomization",
    "MailboxLock",
    "MailboxLockLockedBy",
    "MailboxLockLockedByApiKey",
    "RemoveAccountEmailDomainRequest",
    "ResendAgentSignupCodeRequest",
    "RotateMailboxEmailAddressRequest",
    "SetEmailWebhook200Response",
    "SetEmailWebhook200ResponseData",
    "SetEmailWebhook200ResponseDataWebhook",
    "SetEmailWebhookRequest",
    "SignupChallenge",
    "StartAgentSignup202Response",
    "StartAgentSignup202ResponseData",
    "StartAgentSignupRequest",
    "UpdateEmail200Response",
    "UpdateEmail200ResponseData",
    "UpdateEmailRequest",
    "UpdateMailboxEmailAllowlist200Response",
    "UpdateMailboxEmailAllowlist200ResponseData",
    "UpdateMailboxEmailAllowlistRequest",
    "UpdateMailboxEmailAllowlistRequestSenderAllowlist",
    "VerifyAccountEmailDomainRequest",
    "VerifyAgentSignup200Response",
    "VerifyAgentSignup200ResponseData",
    "VerifyAgentSignup200ResponseDataSignup",
    "VerifyAgentSignup201Response",
    "VerifyAgentSignup201ResponseData",
    "VerifyAgentSignup201ResponseDataAccount",
    "VerifyAgentSignup201ResponseDataMailbox",
    "VerifyAgentSignup201ResponseDataSignup",
    "VerifyAgentSignupRequest",
]

# import apis into sdk package
from revdoku_api.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from revdoku_api.api_response import ApiResponse as ApiResponse
from revdoku_api.api_client import ApiClient as ApiClient
from revdoku_api.configuration import Configuration as Configuration
from revdoku_api.exceptions import OpenApiException as OpenApiException
from revdoku_api.exceptions import ApiTypeError as ApiTypeError
from revdoku_api.exceptions import ApiValueError as ApiValueError
from revdoku_api.exceptions import ApiKeyError as ApiKeyError
from revdoku_api.exceptions import ApiAttributeError as ApiAttributeError
from revdoku_api.exceptions import ApiException as ApiException

# import models into sdk package
from revdoku_api.models.account_identity import AccountIdentity as AccountIdentity
from revdoku_api.models.account_identity_agency_account import AccountIdentityAgencyAccount as AccountIdentityAgencyAccount
from revdoku_api.models.account_identity_permissions import AccountIdentityPermissions as AccountIdentityPermissions
from revdoku_api.models.account_limits import AccountLimits as AccountLimits
from revdoku_api.models.account_pagination import AccountPagination as AccountPagination
from revdoku_api.models.api_error import ApiError as ApiError
from revdoku_api.models.api_error_error import ApiErrorError as ApiErrorError
from revdoku_api.models.api_error_not import ApiErrorNot as ApiErrorNot
from revdoku_api.models.api_success import ApiSuccess as ApiSuccess
from revdoku_api.models.create_account_email_domain_request import CreateAccountEmailDomainRequest as CreateAccountEmailDomainRequest
from revdoku_api.models.create_client_account201_response import CreateClientAccount201Response as CreateClientAccount201Response
from revdoku_api.models.create_client_account201_response_data import CreateClientAccount201ResponseData as CreateClientAccount201ResponseData
from revdoku_api.models.create_client_account_request import CreateClientAccountRequest as CreateClientAccountRequest
from revdoku_api.models.create_mailbox201_response import CreateMailbox201Response as CreateMailbox201Response
from revdoku_api.models.create_mailbox201_response_data import CreateMailbox201ResponseData as CreateMailbox201ResponseData
from revdoku_api.models.create_mailbox_email_alias_request import CreateMailboxEmailAliasRequest as CreateMailboxEmailAliasRequest
from revdoku_api.models.create_mailbox_request import CreateMailboxRequest as CreateMailboxRequest
from revdoku_api.models.create_mailbox_request_mailbox import CreateMailboxRequestMailbox as CreateMailboxRequestMailbox
from revdoku_api.models.create_mailbox_request_mailbox_email import CreateMailboxRequestMailboxEmail as CreateMailboxRequestMailboxEmail
from revdoku_api.models.decoded_email_address import DecodedEmailAddress as DecodedEmailAddress
from revdoku_api.models.decoded_incoming_message import DecodedIncomingMessage as DecodedIncomingMessage
from revdoku_api.models.decoded_incoming_message_attachments_inner import DecodedIncomingMessageAttachmentsInner as DecodedIncomingMessageAttachmentsInner
from revdoku_api.models.download_email_original200_response import DownloadEmailOriginal200Response as DownloadEmailOriginal200Response
from revdoku_api.models.download_email_original200_response_data import DownloadEmailOriginal200ResponseData as DownloadEmailOriginal200ResponseData
from revdoku_api.models.email_attachment import EmailAttachment as EmailAttachment
from revdoku_api.models.email_detail import EmailDetail as EmailDetail
from revdoku_api.models.email_download import EmailDownload as EmailDownload
from revdoku_api.models.email_forwarding import EmailForwarding as EmailForwarding
from revdoku_api.models.email_forwarding_content import EmailForwardingContent as EmailForwardingContent
from revdoku_api.models.email_pagination import EmailPagination as EmailPagination
from revdoku_api.models.email_received_event import EmailReceivedEvent as EmailReceivedEvent
from revdoku_api.models.email_received_event_data import EmailReceivedEventData as EmailReceivedEventData
from revdoku_api.models.email_sender_allowlist import EmailSenderAllowlist as EmailSenderAllowlist
from revdoku_api.models.email_summary import EmailSummary as EmailSummary
from revdoku_api.models.email_summary_files import EmailSummaryFiles as EmailSummaryFiles
from revdoku_api.models.file_pagination import FilePagination as FilePagination
from revdoku_api.models.get_account200_response import GetAccount200Response as GetAccount200Response
from revdoku_api.models.get_account_limits200_response import GetAccountLimits200Response as GetAccountLimits200Response
from revdoku_api.models.get_account_limits200_response_data import GetAccountLimits200ResponseData as GetAccountLimits200ResponseData
from revdoku_api.models.get_account_limits200_response_data_usage import GetAccountLimits200ResponseDataUsage as GetAccountLimits200ResponseDataUsage
from revdoku_api.models.get_account_limits200_response_data_usage_mailbox_creations import GetAccountLimits200ResponseDataUsageMailboxCreations as GetAccountLimits200ResponseDataUsageMailboxCreations
from revdoku_api.models.get_email200_response import GetEmail200Response as GetEmail200Response
from revdoku_api.models.get_email200_response_data import GetEmail200ResponseData as GetEmail200ResponseData
from revdoku_api.models.get_email_subscription200_response import GetEmailSubscription200Response as GetEmailSubscription200Response
from revdoku_api.models.get_email_subscription200_response_data import GetEmailSubscription200ResponseData as GetEmailSubscription200ResponseData
from revdoku_api.models.get_email_subscription200_response_data_subscription import GetEmailSubscription200ResponseDataSubscription as GetEmailSubscription200ResponseDataSubscription
from revdoku_api.models.get_email_webhook200_response import GetEmailWebhook200Response as GetEmailWebhook200Response
from revdoku_api.models.get_email_webhook200_response_data import GetEmailWebhook200ResponseData as GetEmailWebhook200ResponseData
from revdoku_api.models.get_email_webhook200_response_data_webhook import GetEmailWebhook200ResponseDataWebhook as GetEmailWebhook200ResponseDataWebhook
from revdoku_api.models.get_mailbox_email_settings200_response import GetMailboxEmailSettings200Response as GetMailboxEmailSettings200Response
from revdoku_api.models.get_revdoku_status200_response import GetRevdokuStatus200Response as GetRevdokuStatus200Response
from revdoku_api.models.get_revdoku_status200_response_data import GetRevdokuStatus200ResponseData as GetRevdokuStatus200ResponseData
from revdoku_api.models.get_revdoku_status200_response_data_connection import GetRevdokuStatus200ResponseDataConnection as GetRevdokuStatus200ResponseDataConnection
from revdoku_api.models.get_revdoku_status200_response_data_connection_renewal import GetRevdokuStatus200ResponseDataConnectionRenewal as GetRevdokuStatus200ResponseDataConnectionRenewal
from revdoku_api.models.get_revdoku_status200_response_data_features import GetRevdokuStatus200ResponseDataFeatures as GetRevdokuStatus200ResponseDataFeatures
from revdoku_api.models.get_revdoku_status200_response_not import GetRevdokuStatus200ResponseNot as GetRevdokuStatus200ResponseNot
from revdoku_api.models.list_accounts200_response import ListAccounts200Response as ListAccounts200Response
from revdoku_api.models.list_accounts200_response_data import ListAccounts200ResponseData as ListAccounts200ResponseData
from revdoku_api.models.list_emails200_response import ListEmails200Response as ListEmails200Response
from revdoku_api.models.list_emails200_response_data import ListEmails200ResponseData as ListEmails200ResponseData
from revdoku_api.models.list_mailbox_files200_response import ListMailboxFiles200Response as ListMailboxFiles200Response
from revdoku_api.models.list_mailbox_files200_response_data import ListMailboxFiles200ResponseData as ListMailboxFiles200ResponseData
from revdoku_api.models.list_mailboxes200_response import ListMailboxes200Response as ListMailboxes200Response
from revdoku_api.models.list_mailboxes200_response_data import ListMailboxes200ResponseData as ListMailboxes200ResponseData
from revdoku_api.models.mailbox import Mailbox as Mailbox
from revdoku_api.models.mailbox_action import MailboxAction as MailboxAction
from revdoku_api.models.mailbox_email import MailboxEmail as MailboxEmail
from revdoku_api.models.mailbox_email_activity import MailboxEmailActivity as MailboxEmailActivity
from revdoku_api.models.mailbox_email_aliases_inner import MailboxEmailAliasesInner as MailboxEmailAliasesInner
from revdoku_api.models.mailbox_email_assignment import MailboxEmailAssignment as MailboxEmailAssignment
from revdoku_api.models.mailbox_email_assignment_error import MailboxEmailAssignmentError as MailboxEmailAssignmentError
from revdoku_api.models.mailbox_email_available_domains_inner import MailboxEmailAvailableDomainsInner as MailboxEmailAvailableDomainsInner
from revdoku_api.models.mailbox_email_customization import MailboxEmailCustomization as MailboxEmailCustomization
from revdoku_api.models.mailbox_lock import MailboxLock as MailboxLock
from revdoku_api.models.mailbox_lock_locked_by import MailboxLockLockedBy as MailboxLockLockedBy
from revdoku_api.models.mailbox_lock_locked_by_api_key import MailboxLockLockedByApiKey as MailboxLockLockedByApiKey
from revdoku_api.models.remove_account_email_domain_request import RemoveAccountEmailDomainRequest as RemoveAccountEmailDomainRequest
from revdoku_api.models.resend_agent_signup_code_request import ResendAgentSignupCodeRequest as ResendAgentSignupCodeRequest
from revdoku_api.models.rotate_mailbox_email_address_request import RotateMailboxEmailAddressRequest as RotateMailboxEmailAddressRequest
from revdoku_api.models.set_email_webhook200_response import SetEmailWebhook200Response as SetEmailWebhook200Response
from revdoku_api.models.set_email_webhook200_response_data import SetEmailWebhook200ResponseData as SetEmailWebhook200ResponseData
from revdoku_api.models.set_email_webhook200_response_data_webhook import SetEmailWebhook200ResponseDataWebhook as SetEmailWebhook200ResponseDataWebhook
from revdoku_api.models.set_email_webhook_request import SetEmailWebhookRequest as SetEmailWebhookRequest
from revdoku_api.models.signup_challenge import SignupChallenge as SignupChallenge
from revdoku_api.models.start_agent_signup202_response import StartAgentSignup202Response as StartAgentSignup202Response
from revdoku_api.models.start_agent_signup202_response_data import StartAgentSignup202ResponseData as StartAgentSignup202ResponseData
from revdoku_api.models.start_agent_signup_request import StartAgentSignupRequest as StartAgentSignupRequest
from revdoku_api.models.update_email200_response import UpdateEmail200Response as UpdateEmail200Response
from revdoku_api.models.update_email200_response_data import UpdateEmail200ResponseData as UpdateEmail200ResponseData
from revdoku_api.models.update_email_request import UpdateEmailRequest as UpdateEmailRequest
from revdoku_api.models.update_mailbox_email_allowlist200_response import UpdateMailboxEmailAllowlist200Response as UpdateMailboxEmailAllowlist200Response
from revdoku_api.models.update_mailbox_email_allowlist200_response_data import UpdateMailboxEmailAllowlist200ResponseData as UpdateMailboxEmailAllowlist200ResponseData
from revdoku_api.models.update_mailbox_email_allowlist_request import UpdateMailboxEmailAllowlistRequest as UpdateMailboxEmailAllowlistRequest
from revdoku_api.models.update_mailbox_email_allowlist_request_sender_allowlist import UpdateMailboxEmailAllowlistRequestSenderAllowlist as UpdateMailboxEmailAllowlistRequestSenderAllowlist
from revdoku_api.models.verify_account_email_domain_request import VerifyAccountEmailDomainRequest as VerifyAccountEmailDomainRequest
from revdoku_api.models.verify_agent_signup200_response import VerifyAgentSignup200Response as VerifyAgentSignup200Response
from revdoku_api.models.verify_agent_signup200_response_data import VerifyAgentSignup200ResponseData as VerifyAgentSignup200ResponseData
from revdoku_api.models.verify_agent_signup200_response_data_signup import VerifyAgentSignup200ResponseDataSignup as VerifyAgentSignup200ResponseDataSignup
from revdoku_api.models.verify_agent_signup201_response import VerifyAgentSignup201Response as VerifyAgentSignup201Response
from revdoku_api.models.verify_agent_signup201_response_data import VerifyAgentSignup201ResponseData as VerifyAgentSignup201ResponseData
from revdoku_api.models.verify_agent_signup201_response_data_account import VerifyAgentSignup201ResponseDataAccount as VerifyAgentSignup201ResponseDataAccount
from revdoku_api.models.verify_agent_signup201_response_data_mailbox import VerifyAgentSignup201ResponseDataMailbox as VerifyAgentSignup201ResponseDataMailbox
from revdoku_api.models.verify_agent_signup201_response_data_signup import VerifyAgentSignup201ResponseDataSignup as VerifyAgentSignup201ResponseDataSignup
from revdoku_api.models.verify_agent_signup_request import VerifyAgentSignupRequest as VerifyAgentSignupRequest

